name: publish-docker
on:
  push:
    branches:
      - master
  schedule:
    # Weekly on Sundays at 02:00
    - cron: '0 2 * * 0'

env:
  CONTAINER_NAME: ${{ github.repository }} # user/repo format

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Build Image and Push to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: $CONTAINER_NAME
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        cache: ${{ github.event_name != 'schedule' }}
